### ISSUE TITLE
Where is the text data that matches the image?

### ISSUE THREAD

**Issue by wuzhi19931128** [pooooobzx/Vision-Language-Consistency#1]
Only images and answers were found in the dataset, but no corresponding text data was found. Did I miss something?

**Comment by wyattz23** [comment]
Hi, sorry for this confusion, we have updated our drive to include all the text. Note that the current dataset released is just a sample containing 100 of data points and we will release the full data in few weeks soon!

**Comment by wyattz23** [comment]
We have updated the full dataset in the drive. Sampled dataset from full dataset we used for experiment is in a separate folder.

**Comment by wuzhi19931128** [comment]
thanks, i download the full dataset.  It seems that there is an alignment issue with the text and images in the "Knowledge Access Full" folder. The images and PDF folders are consistent,  the text and answer folders are  consistent，even though they are different from each other.  The other three tasks are okay.

Thank you for your time and support

**Comment by wyattz23** [comment]
> thanks, i download the full dataset. It seems that there is an alignment issue with the text and images in the "Knowledge Access Full" folder. The images and PDF folders are consistent, the text and answer folders are consistent，even though they are different from each other. The other three tasks are okay.
> 
> Thank you for your time and support

We have fixed this issue. Also we have updated equation datasets as the prompt used should be "giving the answer without steps" in the picture as GPT will do text conversion automatically if not, and this will affect modality separation. We have updated our dataset now and it should be fine. Check it out!
best
Xiang
